
import React, { useState, useEffect, useCallback, useRef } from 'react';
import { MazeConfig, Cell, Point, MazeShape, MazeTheme, ThemeId, GeneratedMaze, Difficulty } from './types';
import { generateMaze } from './services/mazeLogic';
import { generateMazeStory } from './services/geminiService';
import { jsPDF } from 'jspdf';

const MAZE_THEMES: MazeTheme[] = [
  { id: 'classic', name: 'Classic Labyrinth', bgColor: '#f8fafc', wallColor: '#334155', pathColor: '#ef4444', startColor: '#22c55e', endColor: '#3b82f6', icon: 'fa-monument' },
  { id: 'nightmare', name: 'Midnight Nightmare', bgColor: '#0f172a', wallColor: '#f43f5e', pathColor: '#f8fafc', startColor: '#a855f7', endColor: '#ffffff', icon: 'fa-ghost' },
  { id: 'enchanted', name: 'Enchanted Forest', bgColor: '#f0fdf4', wallColor: '#166534', pathColor: '#fbbf24', startColor: '#ffffff', endColor: '#ec4899', icon: 'fa-tree' },
  { id: 'cyberpunk', name: 'Neon Cyberpunk', bgColor: '#000000', wallColor: '#06b6d4', pathColor: '#f472b6', startColor: '#4ade80', endColor: '#fbbf24', icon: 'fa-microchip' },
  { id: 'parchment', name: 'Ancient Scroll', bgColor: '#fdf6e3', wallColor: '#586e75', pathColor: '#268bd2', startColor: '#d33682', endColor: '#859900', icon: 'fa-scroll' },
  { id: 'ocean', name: 'Deep Ocean', bgColor: '#e0f2fe', wallColor: '#1e3a8a', pathColor: '#f97316', startColor: '#ffffff', endColor: '#06b6d4', icon: 'fa-water' }
];

const SHAPES: { id: MazeShape; icon: string }[] = [
  { id: 'square', icon: 'fa-square' }, { id: 'circle', icon: 'fa-circle' }, { id: 'diamond', icon: 'fa-gem' }, { id: 'cross', icon: 'fa-plus' },
  { id: 'triangle', icon: 'fa-caret-up' }, { id: 'hexagon', icon: 'fa-vector-square' }, { id: 'octagon', icon: 'fa-stop' }, { id: 'star', icon: 'fa-star' },
  { id: 'heart', icon: 'fa-heart' }, { id: 'moon', icon: 'fa-moon' }, { id: 'arrow', icon: 'fa-arrow-up' }, { id: 'donut', icon: 'fa-dot-circle' },
];

const DIFFICULTIES: Difficulty[] = ['easy', 'medium', 'hard'];

const App: React.FC = () => {
  const [config, setConfig] = useState<MazeConfig>({
    size: 20, cellSize: 20, shape: 'square', difficulty: 'hard', showSolution: false,
    showMarks: true, seed: Math.random().toString(36).substring(7), themeId: 'classic',
    wallThickness: 2, pathThickness: 3,
    pdfHeader: 'Labyrinth Architect Challenge',
    pdfFooter: 'Keep Exploring the Labyrinth',
    pdfCredits: 'Generated by Labyrinth Architect AI',
    showSignatureFields: true,
    randomizeShapes: true,
    randomizeDifficulty: true
  });

  const [activeTab, setActiveTab] = useState<'puzzle' | 'answer'>('puzzle');
  const [mazeData, setMazeData] = useState<{ grid: Cell[][]; start: Point; end: Point; solution: Point[]; } | null>(null);
  const [story, setStory] = useState<string>("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [bulkCount, setBulkCount] = useState(5);
  const canvasRef = useRef<HTMLCanvasElement>(null);

  const currentTheme = MAZE_THEMES.find(t => t.id === config.themeId) || MAZE_THEMES[0];

  const handleGenerate = useCallback(async () => {
    setIsGenerating(true);
    const data = generateMaze(config);
    setMazeData(data);
    const storyText = await generateMazeStory(config);
    setStory(storyText);
    setIsGenerating(false);
  }, [config]);

  useEffect(() => { handleGenerate(); }, []);

  const drawMazeToContext = (ctx: CanvasRenderingContext2D, data: any, cfg: MazeConfig, theme: MazeTheme, forceSolution: boolean = false) => {
    const { grid, start, end, solution } = data;
    const { cellSize, showMarks, wallThickness, pathThickness } = cfg;
    ctx.fillStyle = theme.bgColor;
    ctx.fillRect(0, 0, cfg.size * cellSize, cfg.size * cellSize);
    grid.forEach((row: Cell[]) => {
      row.forEach(cell => {
        if (!cell.isInside) return;
        const x = cell.x * cellSize, y = cell.y * cellSize;
        ctx.strokeStyle = theme.wallColor;
        ctx.lineWidth = wallThickness;
        if (cell.walls.top) { ctx.beginPath(); ctx.moveTo(x, y); ctx.lineTo(x + cellSize, y); ctx.stroke(); }
        if (cell.walls.right) { ctx.beginPath(); ctx.moveTo(x + cellSize, y); ctx.lineTo(x + cellSize, y + cellSize); ctx.stroke(); }
        if (cell.walls.bottom) { ctx.beginPath(); ctx.moveTo(x + cellSize, y + cellSize); ctx.lineTo(x, y + cellSize); ctx.stroke(); }
        if (cell.walls.left) { ctx.beginPath(); ctx.moveTo(x, y + cellSize); ctx.lineTo(x, y); ctx.stroke(); }
      });
    });
    if ((cfg.showSolution || forceSolution) && solution.length > 0) {
      ctx.beginPath(); ctx.strokeStyle = theme.pathColor; ctx.lineWidth = pathThickness; ctx.lineJoin = 'round'; ctx.lineCap = 'round';
      const first = solution[0]; ctx.moveTo(first.x * cellSize + cellSize / 2, first.y * cellSize + cellSize / 2);
      for (let i = 1; i < solution.length; i++) { const p = solution[i]; ctx.lineTo(p.x * cellSize + cellSize / 2, p.y * cellSize + cellSize / 2); }
      ctx.stroke();
    }
    if (showMarks) {
      ctx.fillStyle = theme.startColor; ctx.beginPath(); ctx.arc(start.x * cellSize + cellSize / 2, start.y * cellSize + cellSize / 2, cellSize / 3, 0, Math.PI * 2); ctx.fill();
      ctx.fillStyle = theme.endColor; ctx.beginPath(); ctx.arc(end.x * cellSize + cellSize / 2, end.y * cellSize + cellSize / 2, cellSize / 3, 0, Math.PI * 2); ctx.fill();
    }
  };

  useEffect(() => {
    if (!mazeData || !canvasRef.current) return;
    const canvas = canvasRef.current;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;
    canvas.width = config.size * config.cellSize;
    canvas.height = config.size * config.cellSize;
    drawMazeToContext(ctx, mazeData, config, currentTheme, activeTab === 'answer');
  }, [mazeData, config, currentTheme, activeTab]);

  const addPageDecorations = (doc: jsPDF, pageTitle: string, margin: number, pageWidth: number, pageHeight: number) => {
    // Header
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139); 
    doc.text(config.pdfHeader, pageWidth / 2, margin - 10, { align: 'center' });
    
    // Title
    doc.setFontSize(22);
    doc.setTextColor(30, 41, 59); 
    doc.text(pageTitle, margin, margin + 5);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); 
    doc.text(config.pdfFooter, pageWidth / 2, pageHeight - margin + 10, { align: 'center' });
    
    // Credits
    doc.setFontSize(7);
    doc.text(config.pdfCredits, pageWidth - margin, pageHeight - margin + 10, { align: 'right' });

    // Signature Fields
    if (config.showSignatureFields) {
      const sigY = pageHeight - margin - 5;
      doc.setFontSize(9);
      doc.setTextColor(71, 85, 105);
      doc.text("Completed By: __________________________", margin, sigY);
      doc.text("Checked By: __________________________", pageWidth - margin - 60, sigY);
    }
  };

  const downloadBulkPDF = async () => {
    setIsGenerating(true);
    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const pageWidth = doc.internal.pageSize.getWidth(), pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20, availableWidth = pageWidth - (margin * 2);
    const resScale = 4;
    
    const batch: GeneratedMaze[] = [];
    for (let i = 0; i < bulkCount; i++) {
      // Create a per-maze config based on toggles
      const mazeConfig = { ...config, seed: Math.random().toString(36).substring(7) };
      if (config.randomizeShapes) {
        mazeConfig.shape = SHAPES[Math.floor(Math.random() * SHAPES.length)].id;
      }
      if (config.randomizeDifficulty) {
        mazeConfig.difficulty = DIFFICULTIES[Math.floor(Math.random() * DIFFICULTIES.length)];
      }

      const data = generateMaze(mazeConfig);
      const batchStory = await generateMazeStory(mazeConfig);
      
      const scaledConfig = { ...mazeConfig, cellSize: mazeConfig.cellSize * resScale };
      batch.push({ ...data, story: batchStory, config: scaledConfig });
    }

    const offscreenCanvas = document.createElement('canvas');
    const offCtx = offscreenCanvas.getContext('2d');
    if (!offCtx) return;

    // Puzzles
    batch.forEach((m, idx) => {
      if (idx > 0) doc.addPage();
      addPageDecorations(doc, `Maze Challenge #${idx + 1}`, margin, pageWidth, pageHeight);
      
      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      doc.text(`${m.config.difficulty.toUpperCase()} ${m.config.shape.toUpperCase()} | ${m.story}`, margin, margin + 15, { maxWidth: availableWidth });
      
      offscreenCanvas.width = m.config.size * m.config.cellSize;
      offscreenCanvas.height = m.config.size * m.config.cellSize;
      offCtx.clearRect(0, 0, offscreenCanvas.width, offscreenCanvas.height);
      drawMazeToContext(offCtx, m, m.config, currentTheme, false);
      doc.addImage(offscreenCanvas.toDataURL('image/png'), 'PNG', margin, margin + 25, availableWidth, (offscreenCanvas.height / offscreenCanvas.width) * availableWidth);
    });

    // Answers
    batch.forEach((m, idx) => {
      doc.addPage();
      addPageDecorations(doc, `Solution Key #${idx + 1}`, margin, pageWidth, pageHeight);
      
      offscreenCanvas.width = m.config.size * m.config.cellSize;
      offscreenCanvas.height = m.config.size * m.config.cellSize;
      offCtx.clearRect(0, 0, offscreenCanvas.width, offscreenCanvas.height);
      drawMazeToContext(offCtx, m, m.config, currentTheme, true);
      doc.addImage(offscreenCanvas.toDataURL('image/png'), 'PNG', margin, margin + 25, availableWidth, (offscreenCanvas.height / offscreenCanvas.width) * availableWidth);
    });

    doc.save(`labyrinth-pack-${bulkCount}.pdf`);
    setIsGenerating(false);
  };

  return (
    <div className="min-h-screen flex flex-col">
      <header className="bg-white border-b border-slate-200 px-6 py-4 flex items-center justify-between sticky top-0 z-50">
        <div className="flex items-center gap-3">
          <div className="bg-indigo-600 w-10 h-10 rounded-lg flex items-center justify-center text-white shadow-lg shadow-indigo-200">
            <i className="fas fa-project-diagram text-xl"></i>
          </div>
          <div>
            <h1 className="text-xl font-bold text-slate-800 tracking-tight">Labyrinth Architect</h1>
            <p className="text-xs text-slate-500 font-medium uppercase tracking-widest">Advanced Bulk Engine</p>
          </div>
        </div>
        <div className="flex gap-2">
          <div className="flex items-center bg-indigo-50 border border-indigo-100 rounded-lg overflow-hidden h-10">
            <input type="number" min="1" max="50" value={bulkCount} onChange={(e) => setBulkCount(parseInt(e.target.value))} className="w-12 bg-transparent text-center text-sm font-bold text-indigo-700 outline-none" />
            <button onClick={downloadBulkPDF} disabled={isGenerating} className="px-4 py-2 bg-indigo-600 text-white text-xs font-bold hover:bg-indigo-700 transition-all">GENERATE BOOKLET</button>
          </div>
          <button onClick={handleGenerate} disabled={isGenerating} className="px-5 py-2 bg-slate-800 rounded-lg text-sm font-semibold text-white hover:bg-slate-900 transition-all shadow-md"><i className={`fas fa-sync-alt mr-2 ${isGenerating ? 'animate-spin' : ''}`}></i>New Single</button>
        </div>
      </header>

      <main className="flex-1 container mx-auto p-6 grid grid-cols-1 lg:grid-cols-12 gap-8">
        <div className="lg:col-span-4 space-y-6">
          <div className="bg-white rounded-2xl p-6 shadow-sm border border-slate-200 space-y-5">
            <h2 className="text-lg font-bold text-slate-800 border-b border-slate-100 pb-3">Generation</h2>
            
            <div className="space-y-2">
              <label className="text-xs font-bold uppercase text-slate-500 tracking-wide">Difficulty Level</label>
              <div className="flex bg-slate-100 p-1 rounded-xl">
                {DIFFICULTIES.map(d => (
                  <button key={d} onClick={() => setConfig({...config, difficulty: d})} className={`flex-1 py-1.5 text-xs font-bold rounded-lg transition-all ${config.difficulty === d ? 'bg-white text-indigo-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}>{d.toUpperCase()}</button>
                ))}
              </div>
            </div>

            <div className="space-y-3">
              <div className="flex justify-between items-center text-xs font-bold text-slate-500"><span>Density</span><span className="text-indigo-600">{config.size}x{config.size}</span></div>
              <input type="range" min="10" max="60" step="5" value={config.size} onChange={(e) => setConfig({ ...config, size: parseInt(e.target.value) })} className="w-full h-1.5 bg-slate-100 rounded-lg appearance-none cursor-pointer accent-indigo-600" />
            </div>

            <div className="space-y-2">
              <label className="text-xs font-bold uppercase text-slate-500">Base Shape</label>
              <div className="grid grid-cols-6 gap-2">
                {SHAPES.map(s => (
                  <button key={s.id} onClick={() => setConfig({ ...config, shape: s.id })} className={`h-10 rounded-lg border-2 flex items-center justify-center transition-all ${config.shape === s.id ? 'bg-indigo-50 border-indigo-600 text-indigo-600' : 'bg-white border-slate-100 text-slate-400 hover:border-slate-300'}`} title={s.id}><i className={`fas ${s.icon} text-sm`}></i></button>
                ))}
              </div>
            </div>

            <div className="space-y-3 pt-3 border-t border-slate-100">
              <h3 className="text-xs font-bold uppercase text-slate-500">PDF & Export Settings</h3>
              
              <div className="grid grid-cols-1 gap-2 py-2">
                <label className="flex items-center gap-2 cursor-pointer group">
                  <input type="checkbox" checked={config.randomizeShapes} onChange={(e) => setConfig({...config, randomizeShapes: e.target.checked})} className="w-4 h-4 text-indigo-600 rounded focus:ring-indigo-500" />
                  <span className="text-[11px] font-medium text-slate-600">Mix Shapes in PDF</span>
                </label>
                <label className="flex items-center gap-2 cursor-pointer group">
                  <input type="checkbox" checked={config.randomizeDifficulty} onChange={(e) => setConfig({...config, randomizeDifficulty: e.target.checked})} className="w-4 h-4 text-indigo-600 rounded focus:ring-indigo-500" />
                  <span className="text-[11px] font-medium text-slate-600">Mix Difficulties in PDF</span>
                </label>
                <label className="flex items-center gap-2 cursor-pointer group">
                  <input type="checkbox" checked={config.showSignatureFields} onChange={(e) => setConfig({...config, showSignatureFields: e.target.checked})} className="w-4 h-4 text-indigo-600 rounded focus:ring-indigo-500" />
                  <span className="text-[11px] font-medium text-slate-600">Include 'Completed/Checked By'</span>
                </label>
              </div>

              <div className="space-y-2">
                <div className="space-y-1">
                  <span className="text-[10px] font-bold text-slate-400 uppercase">Page Header</span>
                  <input type="text" value={config.pdfHeader} onChange={(e) => setConfig({...config, pdfHeader: e.target.value})} className="w-full px-3 py-1 bg-slate-50 border border-slate-200 rounded text-xs outline-none" />
                </div>
                <div className="space-y-1">
                  <span className="text-[10px] font-bold text-slate-400 uppercase">Page Footer</span>
                  <input type="text" value={config.pdfFooter} onChange={(e) => setConfig({...config, pdfFooter: e.target.value})} className="w-full px-3 py-1 bg-slate-50 border border-slate-200 rounded text-xs outline-none" />
                </div>
                <div className="space-y-1">
                  <span className="text-[10px] font-bold text-slate-400 uppercase">Credits</span>
                  <input type="text" value={config.pdfCredits} onChange={(e) => setConfig({...config, pdfCredits: e.target.value})} className="w-full px-3 py-1 bg-slate-50 border border-slate-200 rounded text-xs outline-none" />
                </div>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-2 pt-2 border-t border-slate-100">
              {MAZE_THEMES.map(theme => (
                <button key={theme.id} onClick={() => setConfig({ ...config, themeId: theme.id })} className={`flex items-center gap-2 p-2 rounded-lg border-2 text-[10px] font-bold transition-all ${config.themeId === theme.id ? 'bg-indigo-50 border-indigo-600 text-indigo-900' : 'bg-white border-slate-100 hover:border-slate-200 text-slate-500'}`}><div className="w-4 h-4 rounded-full flex items-center justify-center text-[8px]" style={{ backgroundColor: theme.wallColor, color: theme.bgColor }}><i className={`fas ${theme.icon}`}></i></div>{theme.name.split(' ')[0]}</button>
              ))}
            </div>
          </div>

          <div className="bg-indigo-900 rounded-2xl p-6 text-white shadow-xl relative overflow-hidden">
            <div className="absolute top-0 right-0 p-4 opacity-10"><i className="fas fa-scroll text-8xl -rotate-12"></i></div>
            <div className="relative z-10 space-y-3">
              <div className="flex items-center gap-2 text-indigo-300"><i className="fas fa-magic"></i><span className="text-[10px] font-bold uppercase tracking-widest">Chronicle of the Vault</span></div>
              <p className="text-xs leading-relaxed italic font-light maze-font">{story || "Consulting the scrolls..."}</p>
            </div>
          </div>
        </div>

        <div className="lg:col-span-8 flex flex-col gap-6">
          <div className="flex gap-2">
             <button onClick={() => setActiveTab('puzzle')} className={`flex-1 py-3 rounded-t-xl font-bold text-sm transition-all border-b-4 ${activeTab === 'puzzle' ? 'bg-white border-indigo-600 text-indigo-600 shadow-sm' : 'bg-slate-50 border-transparent text-slate-400'}`}>Puzzle Preview</button>
             <button onClick={() => setActiveTab('answer')} className={`flex-1 py-3 rounded-t-xl font-bold text-sm transition-all border-b-4 ${activeTab === 'answer' ? 'bg-white border-indigo-600 text-indigo-600 shadow-sm' : 'bg-slate-50 border-transparent text-slate-400'}`}>Solution Preview</button>
          </div>
          
          <div className="bg-white rounded-b-3xl rounded-tr-3xl p-8 shadow-sm border border-slate-200 flex items-center justify-center min-h-[600px] overflow-auto relative">
             {isGenerating && <div className="absolute inset-0 bg-white/80 backdrop-blur-sm z-20 flex items-center justify-center flex-col gap-4"><div className="w-12 h-12 border-4 border-indigo-600 border-t-transparent rounded-full animate-spin"></div><span className="text-indigo-600 font-bold animate-pulse uppercase tracking-widest text-xs">Architecting...</span></div>}
             <div className="relative group p-4 border border-slate-100 rounded-sm bg-slate-50 shadow-inner">
                <canvas ref={canvasRef} className="rounded-sm shadow-xl transition-transform group-hover:scale-[1.005]" style={{ imageRendering: 'pixelated' }} />
                <div className="absolute -bottom-6 left-0 right-0 text-center text-[10px] text-slate-300 font-bold tracking-widest uppercase">{activeTab === 'puzzle' ? 'Live Challenge' : 'Secret Path'}</div>
             </div>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="bg-slate-100 p-4 rounded-xl border border-slate-200 flex items-center gap-4">
              <div className="w-10 h-10 rounded-full flex items-center justify-center text-white shrink-0 shadow-sm" style={{ backgroundColor: currentTheme.startColor }}><i className="fas fa-fingerprint"></i></div>
              <div><p className="text-[10px] uppercase font-bold text-slate-400">Seed</p><p className="text-sm font-bold text-slate-700">{config.seed.toUpperCase()}</p></div>
            </div>
            <div className="bg-slate-100 p-4 rounded-xl border border-slate-200 flex items-center gap-4">
              <div className="w-10 h-10 rounded-full flex items-center justify-center text-white shrink-0 shadow-sm" style={{ backgroundColor: currentTheme.endColor }}><i className="fas fa-flag-checkered"></i></div>
              <div><p className="text-[10px] uppercase font-bold text-slate-400">Exit Point</p><p className="text-sm font-bold text-slate-700">{mazeData?.end.x}, {mazeData?.end.y}</p></div>
            </div>
            <div className="bg-slate-100 p-4 rounded-xl border border-slate-200 flex items-center gap-4">
              <div className="bg-slate-700 w-10 h-10 rounded-full flex items-center justify-center text-white shrink-0 shadow-sm"><i className="fas fa-layer-group"></i></div>
              <div><p className="text-[10px] uppercase font-bold text-slate-400">Complexity</p><p className="text-sm font-bold text-slate-700">{mazeData?.solution.length} Segments</p></div>
            </div>
          </div>
        </div>
      </main>

      <footer className="bg-slate-900 text-slate-400 px-6 py-8 mt-auto">
        <div className="container mx-auto grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="space-y-3"><h3 className="text-white font-bold">Labyrinth Architect</h3><p className="text-sm">Random labyrinth generation with spatial masking and AI storytelling. Professional tools for puzzle book authors.</p></div>
          <div className="space-y-3"><h3 className="text-white font-bold">Current Profile</h3><p className="text-xs text-indigo-400 font-mono uppercase">{config.difficulty} {config.shape}</p><p className="text-xs">{bulkCount} mazes ready for batch processing.</p></div>
          <div className="space-y-3"><h3 className="text-white font-bold">Tools</h3><p className="text-xs">Canvas2D • Batch jsPDF • Gemini API • Tailwind</p><div className="flex gap-4 text-xl"><i className="fab fa-react hover:text-white transition-colors cursor-pointer"></i><i className="fas fa-brain hover:text-white transition-colors cursor-pointer"></i><i className="fas fa-file-pdf hover:text-white transition-colors cursor-pointer"></i></div></div>
        </div>
      </footer>
    </div>
  );
};

export default App;
